language: cpp
compiler:
    - gcc
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-4.9 g++-4.9
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo update-alternatives --config gcov
install:
    - git clone https://github.com/ahamez/libsdd.git /tmp/libsdd
script:
    - mkdir build
    - cd build
    - cmake .. -DLIBSDD_PATH=/tmp/libsdd
    - make
