FROM buildpack-deps:jessie-scm

RUN apt-get update\
&& apt-get install --no-install-recommends -y\
      cmake\
      make\
      software-properties-common\
      valgrind\
      lcov\
      g++

RUN curl -L http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download\
|  tar -v -C /tmp -xz\
&& cd /tmp/boost_1_59_0\
&& ./bootstrap.sh --with-libraries=program_options,coroutine,context,system,thread,filesystem\
&& ./b2 -j 4 install\
&& cd /tmp && rm -rf boost_1_59_0

RUN apt-get install -y\
      ninja-build
